name: SonarQube Analysis

on:
  push:
    branches:
      - dev  # Trigger only for pushes to the dev branch
  pull_request:
    branches:
      - dev  # Trigger for pull requests targeting the dev branch

jobs:
  sonarqube:
    runs-on: ubuntu-latest  # Use a suitable runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if you have a different requirements file
      
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Store your SonarQube token in GitHub Secrets
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Your SonarQube server URL (e.g., http://localhost:9000)
        run: |
          sonar-scanner \
            -Dsonar.projectKey=test \
            -Dsonar.sources= . \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=dev